services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=crypto_tracker
      - DB_PASSWORD=hotmail1234
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001/api

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hotmail1234
      POSTGRES_DB: crypto_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
